#!/usr/bin/env python3
"""Safely detach or remove an MCP server managed in the project .omm."""

from __future__ import annotations

import argparse
from pathlib import Path

from project_mcp_registry import apply_removal, plan_removal


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plan or apply removal of an .omm-managed project MCP server."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root (default: current directory).",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply the plan. Without this flag, only print a dry run.",
    )
    parser.add_argument(
        "--delete-generated",
        action="store_true",
        help="Also delete unchanged, hash-matched files generated by this skill.",
    )
    parser.add_argument("server", help="Managed server name to remove.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        plan = plan_removal(
            args.project_root,
            args.server,
            delete_generated=args.delete_generated,
        )
    except ValueError as error:
        raise SystemExit(str(error)) from error

    print(f"mode={'apply' if args.apply else 'dry-run'}")
    for action in plan.actions:
        print(action)
    if not args.apply:
        print("result=no-changes")
        return 0

    apply_removal(plan)
    print(f"removed={args.server}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
